services:
  db:
    image: postgres:15
    container_name: project1_db
    environment:
      POSTGRES_DB: australia_job_scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Evolgroup@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Expose DB port for local development access
    ports:
      - "127.0.0.1:5433:5432"  # Use port 5433 to avoid conflicts
    restart: unless-stopped

  web:
    build: .
    container_name: project1_web
    ports:
      - "8001:8000"    # access via http://<PC-A-LAN-IP>:8001
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME=australia_job_scraper
      - DB_USER=postgres
      - DB_PASSWORD=Evolgroup@123
      - DB_HOST=db
      - DB_PORT=5432  # Internal Docker port
      # Network access configuration
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.0.49
      - CSRF_TRUSTED_ORIGINS=http://localhost:8001,http://127.0.0.1:8001,http://192.168.0.49:8001
      - CORS_ALLOW_ALL_ORIGINS=1
      # Django Admin network access settings
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
