# Generated by Django 4.2.23 on 2025-09-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
