# Generated by Django 4.2.20 on 2025-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_address_line1_company_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
