# Generated by Django 4.2.20 on 2025-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
