# Generated by Django 4.2.20 on 2025-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_jobposting_department'),
        ('companies', '0006_alter_company_address_line1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
