# Generated by Django 4.2 on 2025-08-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('job_category', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('education', 'Education'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('legal', 'Legal'), ('other', 'Other')], default='other', max_length=50)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('work_mode', models.CharField(blank=True, help_text='Remote, Hybrid, On-site, etc.', max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(choices=[('AUD', 'Australian Dollar'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='AUD', max_length=3)),
                ('salary_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10)),
                ('salary_raw_text', models.CharField(blank=True, help_text='Original salary text', max_length=200)),
                ('external_source', models.CharField(default='seek.com.au', max_length=100)),
                ('external_url', models.URLField(help_text='Original job posting URL', unique=True)),
                ('external_id', models.CharField(blank=True, help_text='External system job ID', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('filled', 'Filled')], default='active', max_length=20)),
                ('posted_ago', models.CharField(blank=True, help_text="Relative date like '2 days ago'", max_length=50)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags or skills')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Store any additional scraped data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.location')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['external_source', 'status'], name='jobs_jobpos_externa_6948f0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_category', 'location'], name='jobs_jobpos_job_cat_64458c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'status'], name='jobs_jobpos_company_68d43e_idx'),
        ),
    ]
