# Generated by Django 4.2 on 2025-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('education', 'Education'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('legal', 'Legal'), ('office_support', 'Office Support'), ('drivers_operators', 'Drivers & Operators'), ('technical_engineering', 'Technical & Engineering'), ('production_workers', 'Production Workers'), ('transport_logistics', 'Transport & Logistics'), ('mining_resources', 'Mining & Resources'), ('sales_marketing', 'Sales & Marketing'), ('executive', 'Executive'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
