# Generated by Django 4.2.23 on 2025-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobposting_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('permanent', 'Permanent'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
    ]
