# Generated by Django 4.2.23 on 2025-08-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('jobs', '0003_alter_jobposting_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('module_path', models.CharField(help_text='Python import path to callable, e.g. script.seek_job_scraper_advanced:run', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_days', 'Custom Days Of Month')], default='daily', max_length=20)),
                ('time_of_day', models.TimeField(help_text='Local time in TIME_ZONE to run')),
                ('day_of_week', models.CharField(blank=True, help_text='0-6 (0=Sunday) or mon,tue,... (django-celery-beat format)', max_length=20)),
                ('days_of_month', models.CharField(blank=True, help_text='Comma-separated day numbers like 1,8,15 or */2 for every 2 days', max_length=60)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crontab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='jobs.jobscript')),
            ],
            options={
                'verbose_name': 'Job Scheduler',
                'verbose_name_plural': 'Job Schedulers',
                'ordering': ['-created_at'],
            },
        ),
    ]
