# Generated by Django 4.2.20 on 2025-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobscript_jobscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobscheduler',
            name='frequency',
            field=models.CharField(choices=[('minute', 'Every Minute'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_days', 'Custom Days Of Month')], default='daily', max_length=20),
        ),
    ]
