# Generated by Django 4.2.23 on 2025-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_expired_at_to_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='contact_person_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_closing_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='vacancy_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
