# Generated by Django 4.2.23 on 2025-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobposting_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='preferred_skill',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(blank=True, null=True),
        ),
    ]
