# Generated by Django 4.2.23 on 2025-09-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department'),
        ('jobs', '0008_jobposting_preferred_skill_jobposting_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='companies.department'),
        ),
    ]
