# Generated by Django 4.2.23 on 2025-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobposting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
