# Generated by Django 4.2.23 on 2025-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobposting_contact_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
