# Generated by Django 4.2.20 on 2025-09-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobposting_contact_person_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='preferred_skill',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='vacancy_number',
        ),
    ]
