# Generated by Django 4.2.20 on 2025-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobposting_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='department',
        ),
    ]
