# Generated by Django 4.2.20 on 2025-09-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_jobposting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='preferred_skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
