# Generated by Django 4.2.23 on 2025-09-16 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobposting_preferred_skills_jobposting_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('incremental', models.BooleanField(default=True)),
                ('jobs_fetched', models.PositiveIntegerField(default=0)),
                ('total_synced', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSyncPortalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(max_length=120)),
                ('target_url', models.URLField(blank=True)),
                ('batch_size', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_results', to='jobs.jobsyncrun')),
            ],
            options={
                'ordering': ['portal_name'],
            },
        ),
        migrations.CreateModel(
            name='JobSyncJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=120)),
                ('request_url', models.URLField(blank=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('was_success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portal_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='jobs.jobsyncportalresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='jobs.jobsyncrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
